// Generate SQL to seed Supabase from local markdown content
// Scans `public/curriculum/`, `curriculum/`, and `curriculum_refactoring/`

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const OUTPUT = path.join(ROOT, 'supabase', 'seed.lessons.sql')
const SOURCES = [
	path.join(ROOT, 'public', 'curriculum'),
	path.join(ROOT, 'curriculum'),
	path.join(ROOT, 'curriculum_refactoring')
]

function walkMarkdown(dir, out = []) {
	if (!fs.existsSync(dir)) return out
	for (const entry of fs.readdirSync(dir)) {
		const full = path.join(dir, entry)
		const stat = fs.statSync(full)
		if (stat.isDirectory()) walkMarkdown(full, out)
		else if (entry.toLowerCase().endsWith('.md')) out.push(full)
	}
	return out
}

function slugify(s) {
	return s
		.toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
		.replace(/(^-|-$)/g, '')
}

function sqlEscape(str) {
	return (str || '')
		.replace(/\\/g, '\\\\')
		.replace(/'/g, "''")
}

function firstHeading(md) {
	const m = /^(#|##)\s+(.+)/m.exec(md)
	return m?.[2]?.trim()
}

function parseMetaLinks(md) {
	const blocks = []
	const regex = /```meta[\s\S]*?```/g
	const matches = md.match(regex) || []
	for (const block of matches) {
		const type = /type:\s*(.+)/.exec(block)?.[1]?.trim()
		const url = /url:\s*(.+)/.exec(block)?.[1]?.trim()
		const label = /label:\s*(.+)/.exec(block)?.[1]?.trim()
		if (type && url) blocks.push({ type, url, label })
	}
	return blocks
}

function deriveLevelFromPath(p) {
	const parts = p.split(path.sep)
	for (const part of parts) {
		const lc = part.toLowerCase()
		if (['beginner','advanced','grammar','verbs','vocabulary','numbers','time','introductions','conversation','directions','reference'].includes(lc)) {
			return part
		}
	}
	return 'Beginner'
}

function main() {
    console.log('ROOT', ROOT)
    console.log('SOURCES', SOURCES)
    const files = SOURCES.flatMap(s => walkMarkdown(s))
    console.log('FOUND_MD_COUNT', files.length)
    if (files.length === 0) {
        console.error('No markdown files found to seed.')
        process.exit(1)
    }

	let chapterCounter = 1
	const sql = []
	sql.push('-- Auto-generated by scripts/generateSeedSql.js')
	sql.push('begin;')

	for (const file of files) {
		const md = fs.readFileSync(file, 'utf8')
		const title = firstHeading(md) || path.basename(file, path.extname(file))
		const level = deriveLevelFromPath(file)
		const slug = slugify(title)
		const lessonId = path.relative(ROOT, file).replace(/\\/g, '/')
		const chapter = chapterCounter++

		const insertLesson = `insert into public.lessons (lesson_id, language, level, chapter_number, slug, title, goal_vocabulary_md, status, "order") values ('${sqlEscape(lessonId)}', 'sanskrit', '${sqlEscape(level)}', ${chapter}, '${sqlEscape(slug)}', '${sqlEscape(title)}', '${sqlEscape(md)}', 'published', ${chapter}) on conflict (lesson_id) do update set title=excluded.title, level=excluded.level, chapter_number=excluded.chapter_number, slug=excluded.slug, goal_vocabulary_md=excluded.goal_vocabulary_md, status=excluded.status, "order"=excluded."order";`
		sql.push(insertLesson)

		const links = parseMetaLinks(md)
		for (const link of links) {
			const ins = `insert into public.lesson_meta_links (lesson_id, type, label, url) select id, '${sqlEscape(link.type)}', ${link.label?`'${sqlEscape(link.label)}'`:'null'}, '${sqlEscape(link.url)}' from public.lessons where lesson_id='${sqlEscape(lessonId)}';`
			sql.push(ins)
		}
	}

	sql.push('commit;')
	fs.mkdirSync(path.dirname(OUTPUT), { recursive: true })
	fs.writeFileSync(OUTPUT, sql.join('\n'))
	console.log(`Wrote ${OUTPUT} with ${files.length} lessons.`)
}

main()


